### ISSUE TITLE
Traefik and Home Assistant on the host network

### ISSUE THREAD

**Issue by arnefm** [smarthomeuni/dockerstack#1]
Hi, couldn't find any way to contact you so decided to create this issue.

I stumbled upon your repository and I think you've possibly solved a problem that I have been struggling with. I see that you run traefik on regular docker networks, while Home Assistant is running on the host network - Have you been able to make traefik work with Home Assistant in this configuration?

I've been trying to accomplish this for days without any luck. Any hints or help would be greatly appreciated.

**Comment by pickle-khalil** [comment]
Hey buddy - what you need is some changes to Traefik.toml (note that I am still using v1). Let me know if any issues or more questions. 

this also helps: 
https://community.home-assistant.io/t/trouble-getting-traefik-play-nice-with-ha-in-docker-using-network-mode-host/84757/8?u=leapfrog356

[file]
[backends]
  [backends.backend-homeassistant]
    [backends.backend-homeassistant.servers]
      [backends.backend-homeassistant.servers.server-homeassistant-ext]
        url = "http://<IP OF HOST>:8123"
        weight = 0
[frontends]
  [frontends.frontend-homeassistant]
    backend = "backend-homeassistant"
    passHostHeader = true
    [frontends.frontend-homeassistant.routes]
      [frontends.frontend-homeassistant.routes.route-homeassistant-ext]
      rule = "Host:hass.<YOUR DOMAIN>"

**Comment by arnefm** [comment]
Hi! Thanks for replying. I actually figured this out not long after posting this question - I found a PR for traefik that enables routing through the `docker0` interface! So I managed to get this working perfectly using labels/args only. 

The only thing needed is traefik version 2.2.0 or newer (traefik:latest is apparently older) and making sure the traefik container to resolve the host "host.docker.internal" which should point to the IP-address on your `docker0` interface. See the "extra_hosts" part below.

```
---
version: '3'

services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:${HA_VERSION}
    privileged: true
    restart: unless-stopped
    depends_on:
    network_mode: host
    expose:
      - "8123"
    ports:
      - "8123:8123"
    volumes:
      - /home/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id/:/dev/serial/by-id/
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
    environment:
      - TZ=Europe/Oslo
      - DOMAIN="home."${DOMAIN}""
    healthcheck:
      test: "curl -Lf http://localhost:8123"
      timeout: 10s
      interval: 30s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`home.${DOMAIN}`)"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.tls.certresolver=le"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

  traefik:
    container_name: traefik
    image: traefik:2.2.0
    restart: always
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - EMAIL=${EMAIL}
    command:
      - "--log.level=WARN"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=${EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/acme.json"
      - "--certificatesresolvers.le.acme.tlsChallenge=true"
      - "--certificatesresolvers.le.acme.httpChallenge=true"
      - "--certificatesresolvers.le.acme.httpChallenge.entryPoint=web"
    labels:
      - "traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.http_catchall.entrypoints=web"
      - "traefik.http.routers.http_catchall.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
```

Thank you again for replying to my question - I hope the solution I found is useful to you when you decide to migrate to v2!
